In [6]:
from sklearn.preprocessing import StandardScaler
import os
import time
import pandas as pd
import numpy as np
import librosa


In [2]:
def getFftMfcc(wav):
    y, sr = librosa.load(wav, mono=True)
    mfcc = librosa.feature.mfcc(y=y, sr=sr)
    mfccArr = np.array(mfcc)
    return mfccArr

In [13]:
baseDirectory ="C:\\Users\\Zachary\\Downloads\\nsynth\\nsynth-train\\audio"
audio=[]
scale = StandardScaler()
start=time.time()
for x,y,z in os.walk(baseDirectory):
    for wav in z:
        soundDir = baseDirectory + "\\" + wav
        test=getFftMfcc(soundDir)
        arr = np.delete(test, np.where(test == 0)).reshape(-1, 1)
        arr = np.array(scale.fit_transform(arr)).reshape(arr.size)
        audio.append(arr)
end=time.time()
print(end-start)
print(np.array(audio))
#pd.to_csv(audio)

20053.983436346054
[array([-3.7653105 , -4.525652  , -4.5345325 , ..., -0.02695847,
       -0.02695847, -0.02695847], dtype=float32)
 array([-3.5626736 , -4.557541  , -4.5667567 , ..., -0.02584453,
       -0.02584453, -0.02584453], dtype=float32)
 array([-3.6400123 , -4.4066415 , -4.392719  , ..., -0.02909652,
       -0.02909652, -0.02909652], dtype=float32)
 ...
 array([-5.1748614 , -3.5666323 , -3.5434368 , ...,  0.21250555,
        0.21250555,  0.21250555], dtype=float32)
 array([-4.7225976, -3.5155916, -3.5779989, ...,  0.2137294,  0.2137294,
        0.2137294], dtype=float32)
 array([-4.3036423 , -3.5351734 , -3.6143367 , ...,  0.20966795,
        0.20966795,  0.20966795], dtype=float32)]


In [35]:
for i in range(0,280000,10000):
    pdD=pd.DataFrame(audio[i:i+9999])
    pdD.to_csv('C:\\Users\\Zachary\\Downloads\\nsynth\\train.csv', mode='a', header=False)
pdD=pd.DataFrame(audio[280000:])
pdD.to_csv('C:\\Users\\Zachary\\Downloads\\nsynth\\train.csv', mode='a', header=False)